//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Budgets = new HashSet<Budget>();
            this.PaymentAccounts = new HashSet<PaymentAccount>();
        }
    
        public int AccountKey { get; set; }
        public string AccountName { get; set; }
        public string GLAccountCode { get; set; }
        public Nullable<int> AccountTypeKey { get; set; }
        public string AccountNote { get; set; }
        public Nullable<int> AccountParentKey { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<PaymentAccount> PaymentAccounts { get; set; }
        public virtual AccountType AccountType { get; set; }
    }
}
