//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetKey { get; set; }
        public Nullable<int> BudgetProgramKey { get; set; }
        public Nullable<int> BudgetTermKey { get; set; }
        public Nullable<int> BudgetAccountKey { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public string BudgetNote { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Program Program { get; set; }
        public virtual Term Term { get; set; }
    }
}
