//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantDistribution
    {
        public GrantDistribution()
        {
            this.GrantDistributionPrograms = new HashSet<GrantDistributionProgram>();
        }
    
        public int GrantDistributionKey { get; set; }
        public Nullable<int> GrantDistributionGrantKey { get; set; }
        public Nullable<int> GrantDistributionTermKey { get; set; }
        public Nullable<decimal> GrantDistributionAmountTotal { get; set; }
        public string GrantDistributionInvoiceNumber { get; set; }
        public string GrantDistributionNote { get; set; }
    
        public virtual Grant Grant { get; set; }
        public virtual ICollection<GrantDistributionProgram> GrantDistributionPrograms { get; set; }
        public virtual Term Term { get; set; }
    }
}
