//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantDistributionProgram
    {
        public int GrantDistributionProgramKey { get; set; }
        public Nullable<int> GrantDistributionKey { get; set; }
        public Nullable<int> ProgramKey { get; set; }
        public Nullable<decimal> GrantDistributionProgramAmount { get; set; }
    
        public virtual GrantDistribution GrantDistribution { get; set; }
        public virtual Program Program { get; set; }
    }
}
