//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grant
    {
        public Grant()
        {
            this.GrantDistributions = new HashSet<GrantDistribution>();
        }
    
        public int GrantKey { get; set; }
        public string GrantName { get; set; }
        public string GrantNote { get; set; }
    
        public virtual ICollection<GrantDistribution> GrantDistributions { get; set; }
    }
}
