//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAccount
    {
        public int PaymentAccountKey { get; set; }
        public Nullable<int> PaymentKey { get; set; }
        public Nullable<int> AccountKey { get; set; }
        public Nullable<decimal> PaymentAccountAmount { get; set; }
        public string PaymentAccountNote { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
