//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentAccounts = new HashSet<PaymentAccount>();
            this.PaymentPrograms = new HashSet<PaymentProgram>();
        }
    
        public int PaymentKey { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentTo { get; set; }
        public string PaymentCheckNumber { get; set; }
        public Nullable<int> PaymentTypeKey { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentNote { get; set; }
        public Nullable<byte> PaymentReconciled { get; set; }
        public string PaymentVendorInvoiceNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAccount> PaymentAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentProgram> PaymentPrograms { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
