//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRole
    {
        public PersonRole()
        {
            this.PersonWithRoles = new HashSet<PersonWithRole>();
        }
    
        public int PersonRoleKey { get; set; }
        public string PersonRoleCode { get; set; }
        public string PersonRole1 { get; set; }
        public string PersonRoleDescription { get; set; }
    
        public virtual ICollection<PersonWithRole> PersonWithRoles { get; set; }
    }
}
