//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonWithRoles = new HashSet<PersonWithRole>();
        }
    
        public int PersonKey { get; set; }
        public string PersonName { get; set; }
        public string PersonAddress { get; set; }
        public string PersonCity { get; set; }
        public Nullable<int> PersonStateKey { get; set; }
        public string PersonZipCode { get; set; }
        public string PersonNote { get; set; }
        public string VendorFederalEIN { get; set; }
        public string VendorDefaultTerms { get; set; }
    
        public virtual ICollection<PersonWithRole> PersonWithRoles { get; set; }
    }
}
