//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Budgets = new HashSet<Budget>();
            this.PaymentPrograms = new HashSet<PaymentProgram>();
        }
    
        public int ProgramKey { get; set; }
        public string ProgramName { get; set; }
        public string ProgramNote { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual GrantDistributionProgram GrantDistributionProgram { get; set; }
        public virtual ICollection<PaymentProgram> PaymentPrograms { get; set; }
    }
}
