//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.Budgets = new HashSet<Budget>();
            this.GrantDistributions = new HashSet<GrantDistribution>();
        }
    
        public int TermKey { get; set; }
        public string TermName { get; set; }
        public Nullable<System.DateTime> TermStartDate { get; set; }
        public Nullable<System.DateTime> TermEndDate { get; set; }
        public string TermNote { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<GrantDistribution> GrantDistributions { get; set; }
    }
}
